# Generated by Django 6.0.1 on 2026-01-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('threads_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готово'), ('published', 'Опубликовано'), ('failed', 'Ошибка')], default='draft', max_length=20, verbose_name='Статус')),
                ('ai_optimized', models.BooleanField(default=False, verbose_name='AI-оптимизация')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано в')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='campaigns.campaign')),
                ('threads_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='threads_accounts.threadsaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(verbose_name='Запланировано на')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('scheduled', 'Запланировано'), ('cancelled', 'Отменено'), ('done', 'Выполнено')], default='scheduled', max_length=20, verbose_name='Статус расписания')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='posts.post')),
            ],
            options={
                'verbose_name': 'Расписание поста',
                'verbose_name_plural': 'Расписания постов',
                'ordering': ['scheduled_for'],
            },
        ),
    ]
