# Generated by Django 6.0.1 on 2026-01-25 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_publish_error',
            field=models.TextField(blank=True, verbose_name='Ошибка публикации'),
        ),
        migrations.AddField(
            model_name='post',
            name='threads_thread_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Threads ID'),
        ),
        migrations.CreateModel(
            name='PublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('thread_id', models.CharField(blank=True, max_length=64, verbose_name='Threads ID')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог публикации',
                'verbose_name_plural': 'Логи публикаций',
                'ordering': ['-created_at'],
            },
        ),
    ]
