# Generated by Django 6.0.1 on 2026-05-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_last_publish_error_post_threads_thread_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='threads_permalink',
            field=models.URLField(blank=True, max_length=512, verbose_name='Threads permalink'),
        ),
    ]
