# Generated by Django 6.0.1 on 2026-01-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Снимок на')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Показы')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('replies', models.PositiveIntegerField(default=0, verbose_name='Ответы')),
                ('reposts', models.PositiveIntegerField(default=0, verbose_name='Репосты')),
                ('quotes', models.PositiveIntegerField(default=0, verbose_name='Цитирования')),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Engagement rate')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='posts.post')),
            ],
            options={
                'verbose_name': 'Аналитика поста',
                'verbose_name_plural': 'Аналитика постов',
                'ordering': ['-captured_at'],
            },
        ),
    ]
