# Generated by Django 6.0.1 on 2026-01-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
        ('posts', '0002_post_last_publish_error_post_threads_thread_id_and_more'),
        ('threads_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='Снимок на')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры профиля')),
                ('followers', models.PositiveIntegerField(default=0, verbose_name='Подписчики')),
                ('threads_count', models.PositiveIntegerField(default=0, verbose_name='Постов')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_analytics', to='threads_accounts.threadsaccount')),
            ],
            options={
                'verbose_name': 'Аналитика профиля',
                'verbose_name_plural': 'Аналитика профилей',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadsMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(blank=True)),
                ('permalink', models.URLField(blank=True)),
                ('created_at_remote', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='threads_accounts.threadsaccount')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='posts.post')),
            ],
            options={
                'verbose_name': 'Упоминание',
                'verbose_name_plural': 'Упоминания',
                'ordering': ['-captured_at'],
                'unique_together': {('account', 'remote_id')},
            },
        ),
        migrations.CreateModel(
            name='ThreadsReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('text', models.TextField(blank=True)),
                ('created_at_remote', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='threads_accounts.threadsaccount')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.post')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-captured_at'],
                'unique_together': {('account', 'remote_id')},
            },
        ),
    ]
