from django.urls import path

from .views import (
    accounts_page,
    analytics_page,
    compose_page,
    dashboard,
    features_page,
    history_page,
    home,
    how_page,
    monitoring_page,
    permissions_page,
    privacy_page,
    profile_page,
    publish_post,
    sync_threads_data,
    delete_post_remote,
    posts_page,
    cases_page,
    contacts_page,
    pricing_page,
)

urlpatterns = [
    path("", home, name="home"),
    path("features/", features_page, name="features"),
    path("pricing/", pricing_page, name="pricing"),
    path("cases/", cases_page, name="cases"),
    path("how/", how_page, name="how"),
    path("contacts/", contacts_page, name="contacts"),
    path("dashboard/", dashboard, name="dashboard"),
    path("dashboard/sync/", sync_threads_data, name="dashboard_sync"),
    path("compose/", compose_page, name="compose"),
    path("history/", history_page, name="history"),
    path("monitoring/", monitoring_page, name="monitoring"),
    path("permissions/", permissions_page, name="permissions"),
    path("privacy/", privacy_page, name="privacy"),
    path("posts/", posts_page, name="posts"),
    path("posts/<int:post_id>/publish/", publish_post, name="post_publish"),
    path("posts/<int:post_id>/delete-remote/", delete_post_remote, name="post_delete_remote"),
    path("accounts/", accounts_page, name="accounts"),
    path("analytics/", analytics_page, name="analytics"),
    path("profile/", profile_page, name="profile"),
]
