# Generated by Django 6.0.1 on 2026-01-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Username')),
                ('access_token', models.CharField(blank=True, max_length=512, verbose_name='Access token')),
                ('refresh_token', models.CharField(blank=True, max_length=512, verbose_name='Refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Threads account',
                'verbose_name_plural': 'Threads accounts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'username')},
            },
        ),
    ]
