# Generated by Django 6.0.1 on 2026-01-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_limit_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит публикаций в день'),
        ),
    ]
