# Generated by Django 6.0.1 on 2026-02-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_daily_limit_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание пробного тарифа'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Старт пробного тарифа'),
        ),
    ]
