# Generated by Django 6.0.1 on 2026-01-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Пауза'), ('completed', 'Завершена')], default='draft', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Старт')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Финиш')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ['-created_at'],
            },
        ),
    ]
