# Generated by Django 6.0.1 on 2026-01-25 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_company_companyapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapplication',
            name='approved_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='campaigns.company'),
        ),
    ]
