# Generated by Django 6.0.1 on 2026-05-31 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название пака')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во постов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scraped Pack',
                'verbose_name_plural': 'Scraped Packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('replies', models.PositiveIntegerField(default=0, verbose_name='Комменты')),
                ('reposts', models.PositiveIntegerField(default=0, verbose_name='Репосты')),
                ('lang', models.CharField(default='ru', max_length=8, verbose_name='Язык')),
                ('entities', models.JSONField(default=list, verbose_name='Сущности')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ai_generator.scrapedpack')),
            ],
            options={
                'verbose_name': 'Scraped Post',
                'verbose_name_plural': 'Scraped Posts',
                'ordering': ['-likes'],
            },
        ),
    ]
